### ISSUE TITLE
Can't install this package on Bun

### ISSUE THREAD

**Issue by zainphp** [sensasi-delight/mui-datatables#7]
log:

```bash
Blocked 3 postinstalls. Run `bun pm untrusted` for details.

D:\SensasiApp\ekbs-nextjs>bun pm untrusted
[0.00ms] ".env.local"
bun pm untrusted v1.1.40 (b5b51004)

.\node_modules\mui-datatables @github:sensasi-delight/mui-datatables#fbe1672
 » [prepare]: npm run build

.\node_modules\core-js-pure @3.39.0
 » [postinstall]: node -e "try{require('./postinstall')}catch(e){}"

.\node_modules\@sentry\cli @2.39.1
 » [postinstall]: node ./scripts/install.js

These dependencies had their lifecycle scripts blocked during install.

If you trust them and wish to run their scripts, use `bun pm trust`.

D:\SensasiApp\ekbs-nextjs>bun pm trust
[0.00ms] ".env.local"
bun pm trust v1.1.40 (b5b51004)
error: expected package names(s) or --all

D:\SensasiApp\ekbs-nextjs>bun pm trust --all
[0.00ms] ".env.local"
bun pm trust v1.1.40 (b5b51004)
  ⚙️  @sentry/cli [1/3] $ cross-env NODE_ENV=production bun x rollup -c
(node:16360) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
[!] RollupError: Node tried to load your configuration file as CommonJS even though it is likely an ES module. To resolve this, change the extension of your configuration to ".mjs", set "type": "module" in your package.json file or pass the "--bundleConfigAsCjs" flag.        

Original error: Cannot use import statement outside a module
https://rollupjs.org/command-line-interface/#bundleconfigascjs
D:\SensasiApp\ekbs-nextjs\node_modules\mui-datatables\rollup.config.js:1
import babel from '@rollup/plugin-babel';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1205:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at cjsLoader (node:internal/modules/esm/translators:284:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:234:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:316:24)


error: script "build" exited with code 1

error: prepare script from "mui-datatables" exited with 1
```

**Comment by zainphp** [comment]
new error:
```bash
D:\SensasiApp\ekbs-nextjs>bun pm trust --all                                            
[0.00ms] ".env.local"
bun pm trust v1.1.40 (b5b51004)
  ⚙️  core-js-pure [1/3] $ cross-env NODE_ENV=production bun x rollup -c
[!] Error: Cannot find package '@rollup/plugin-babel' imported from D:\SensasiApp\ekbs-nextjs\node_modules\mui-datatables\rollup.config.mjs
    at new NodeError (node:internal/errors:406:5)
    at packageResolve (node:internal/modules/esm/resolve:789:9)
    at moduleResolve (node:internal/modules/esm/resolve:838:20)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36)


error: script "build" exited with code 1

error: prepare script from "mui-datatables" exited with 1

D:\SensasiApp\ekbs-nextjs>
```

**Comment by zainphp** [comment]
new error:

```bash
D:\SensasiApp\ekbs-nextjs>bun add github:sensasi-delight/mui-datatables                                  
[0.00ms] ".env.local"
bun add v1.1.40 (b5b51004)

+ xlsx@https://cdn.sheetjs.com/xlsx-0.20.3/xlsx-0.20.3.tgz

installed mui-datatables@github:sensasi-delight/mui-datatables#43a06f6

4 packages installed [3.35s]

Blocked 1 postinstall. Run `bun pm untrusted` for details.

D:\SensasiApp\ekbs-nextjs>bun pm trust --all
[0.00ms] ".env.local"
bun pm trust v1.1.40 (b5b51004)
  ⚙️  sharp [1/2] $ cross-env NODE_ENV=production bun x rollup -c
[!] Error: Cannot find package '@rollup/plugin-babel' imported from D:\SensasiApp\ekbs-nextjs\node_modules\mui-datatables\rollup.config.mjs
    at new NodeError (node:internal/errors:406:5)
    at packageResolve (node:internal/modules/esm/resolve:789:9)
    at moduleResolve (node:internal/modules/esm/resolve:838:20)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36)


error: script "build" exited with code 1

error: prepare script from "mui-datatables" exited with 1

D:\SensasiApp\ekbs-nextjs>
```

**Comment by zainphp** [comment]
new error:

```bash
D:\SensasiApp\ekbs-nextjs>bun uninstall @rollup/plugin-replace mui-datatables @rollup/plugin-babel
[0.00ms] ".env.local"
bun remove v1.1.40 (b5b51004)

+ xlsx@https://cdn.sheetjs.com/xlsx-0.20.3/xlsx-0.20.3.tgz

3 packages installed [276.00ms]
Removed: 3

D:\SensasiApp\ekbs-nextjs>bun add github:sensasi-delight/mui-datatables
[1.04ms] ".env.local"
bun add v1.1.40 (b5b51004)
  ⚙️  mui-datatables [1/1] $ cross-env NODE_ENV=production bun x rollup -c
[!] Error: Cannot find package '@rollup/plugin-typescript' imported from D:\SensasiApp\ekbs-nextjs\node_modules\mui-datatables\rollup.config.mjs
    at new NodeError (node:internal/errors:406:5)
    at packageResolve (node:internal/modules/esm/resolve:789:9)
    at moduleResolve (node:internal/modules/esm/resolve:838:20)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36)


error: script "build" exited with code 1

error: prepare script from "mui-datatables" exited with 1

D:\SensasiApp\ekbs-nextjs>
```

**Comment by zainphp** [comment]
new error. capek. new method.

```
D:\SensasiApp\ekbs-nextjs>bun add github:sensasi-delight/mui-datatables
[0.96ms] ".env.local"
bun add v1.1.40 (b5b51004)
  ⚙️  mui-datatables [1/1] $ cross-env NODE_ENV=production bun x rollup -c

src/index.ts → dist/index.js...
(!) Unresolved dependencies
https://rollupjs.org/troubleshooting/#warning-treating-module-as-external-dependency
react/jsx-runtime (imported by "src/components/TablePagination.tsx" and "src/components/ExpandButton.tsx")
@mui/material/TablePagination (imported by "src/components/TablePagination.tsx")
tss-react/mui (imported by "src/components/TablePagination.tsx")
@mui/material/IconButton (imported by "src/components/ExpandButton.tsx")
@mui/icons-material/KeyboardArrowRight (imported by "src/components/ExpandButton.tsx")
@mui/icons-material/Remove (imported by "src/components/ExpandButton.tsx")
[!] (plugin babel) Error: Cannot find package '@babel/plugin-proposal-class-properties' imported from D:\SensasiApp\ekbs-nextjs\node_modules\mui-datatables\babel-virtual-resolve-base.js
src/components/JumpToPage.js
    at new captureLargerStackTrace (D:\SensasiApp\ekbs-nextjs\node_modules\@babel\core\src\vendor\import-meta-resolve.js:460:5)
    at packageResolve (D:\SensasiApp\ekbs-nextjs\node_modules\@babel\core\src\vendor\import-meta-resolve.js:1970:9)
    at packageResolve (D:\SensasiApp\ekbs-nextjs\node_modules\@babel\core\src\vendor\import-meta-resolve.js:2048:18)
    at moduleResolve (D:\SensasiApp\ekbs-nextjs\node_modules\@babel\core\src\vendor\import-meta-resolve.js:2224:15)
    at defaultResolve (D:\SensasiApp\ekbs-nextjs\node_modules\@babel\core\src\vendor\import-meta-resolve.js:2262:12)
    at tryImportMetaResolve (D:\SensasiApp\ekbs-nextjs\node_modules\@babel\core\src\config\files\plugins.ts:154:51)
    at tryImportMetaResolve (D:\SensasiApp\ekbs-nextjs\node_modules\@babel\core\src\config\files\plugins.ts:184:19)
    at resolveStandardizedNameForImport (D:\SensasiApp\ekbs-nextjs\node_modules\@babel\core\src\config\files\plugins.ts:200:22)
    at resolvePlugin (D:\SensasiApp\ekbs-nextjs\node_modules\@babel\core\src\config\files\plugins.ts:38:32)
    at loadPlugin.next (<anonymous>)


error: script "build" exited with code 1

error: prepare script from "mui-datatables" exited with 1

D:\SensasiApp\ekbs-nextjs>
```

**Comment by zainphp** [comment]
new error:

```bash

 ⨯ ./node_modules/mui-datatables/dist/index.js:15:15
Module not found: Can't resolve '@babel/runtime-corejs3/helpers/typeof'
  13 | var _toConsumableArray = require('@babel/runtime-corejs3/helpers/toConsumableArray');
  14 | var _objectWithoutProperties = require('@babel/runtime-corejs3/helpers/objectWithoutProperties'); 
> 15 | var _typeof = require('@babel/runtime-corejs3/helpers/typeof');
     |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  16 | var _classCallCheck = require('@babel/runtime-corejs3/helpers/classCallCheck');
  17 | var _createClass = require('@babel/runtime-corejs3/helpers/createClass');
  18 | var _possibleConstructorReturn = require('@babel/runtime-corejs3/helpers/possibleConstructorReturn');



https://nextjs.org/docs/messages/module-not-found

```

**Comment by zainphp** [comment]
still error

**Comment by zainphp** [comment]
The errors was gone when upgrade the bundling process in #25. close this issue for now.
